Repository icssc/ZotMeal, pull requests merged in 2025-06, with the labels that each got.

#508 Mobile compatability
  apps/next/src/app/about/page.tsx
  apps/next/src/app/events/page.tsx
  apps/next/src/app/page.tsx
  apps/next/src/components/ui/card/event-card.tsx
  apps/next/src/components/ui/card/food-card.tsx
  apps/next/src/components/ui/dishes-info.tsx
  apps/next/src/components/ui/event-drawer-content.tsx
  apps/next/src/components/ui/food-drawer-content.tsx
  apps/next/src/components/ui/shadcn/drawer.tsx
  apps/next/src/components/ui/side.tsx
  apps/next/src/components/ui/status.tsx
  package.json
  pnpm-lock.yaml
Labels: frontend, mobile

#511 📝Next Documentation
  apps/next/README.md
  apps/next/src/components/ui/allergen-badge.tsx
  apps/next/src/components/ui/card/event-card.tsx
  apps/next/src/components/ui/card/food-card.tsx
  apps/next/src/components/ui/contributor.tsx
  apps/next/src/components/ui/dishes-info.tsx
  apps/next/src/components/ui/event-dialog-content.tsx
  apps/next/src/components/ui/food-dialog-content.tsx
  apps/next/src/components/ui/meal-divider.tsx
  apps/next/src/components/ui/ongoing-badge.tsx
  apps/next/src/components/ui/side.tsx
  apps/next/src/components/ui/sidebar/sidebar-button.tsx
  apps/next/src/components/ui/sidebar/sidebar-content.tsx
  apps/next/src/components/ui/sidebar/sidebar-divider.tsx
  apps/next/src/components/ui/status.tsx
  apps/next/src/components/ui/toolbar.tsx
  apps/next/src/context/date-context.tsx
  apps/next/src/hooks/useMediaQuery.ts
  docs/About.md
  docs/Database Schema.md
  docs/Frontend - Expo.md
  docs/Frontend.md
  docs/Getting Started.md
  docs/Serverless Functions.md
  packages/api/README.md
  packages/api/src/server/README.md
Labels: docs

#512 ✨Add ingredients field, fix sub-nutrition, fix sugar
  apps/next/src/components/ingredients-dialog.tsx
  apps/next/src/components/ui/card/food-card.tsx
  apps/next/src/components/ui/food-dialog-content.tsx
  apps/next/src/utils/types.ts
  packages/api/src/server/daily/parse.ts
  packages/db/src/schema/dishes.ts
  packages/db/src/schema/nutritionInfos.ts
  packages/validators/src/campusdish/models.ts
Labels: bug, backend

#513 👥 Add contributors fetching
  apps/next/src/app/about/page.tsx
  apps/next/src/components/ui/contributor.tsx
  packages/api/package.json
  packages/api/src/contributors/services.ts
  packages/api/src/root.ts
  packages/api/src/server/scrapeEvents/index.ts
  packages/api/src/server/weekly/index.ts
  packages/db/src/schema/contributors.ts
  packages/db/src/schema/index.ts
  pnpm-lock.yaml
Labels: enhancement, frontend, backend
